services:
  api:
    image: api:latest
    build:
      context: repo-stat
      dockerfile: Dockerfile.api
    container_name: api
    restart: unless-stopped
    ports:
      - "28080:8080"
    environment:
      - PROCESSOR_ADDRESS=processor:50052
      - SUBSCRIBER_ADDRESS=subscriber:50053
    depends_on:
      - processor
      - subscriber
    networks:
      - repo-stat
    volumes:
      - ./repo-stat/api/config/config.yaml:/config.yaml

  subscriber:
    image: subscriber:latest
    build:
      context: repo-stat
      dockerfile: Dockerfile.subscriber
    container_name: subscriber
    restart: unless-stopped
    ports:
      - "50053:50053"
    volumes:
      - ./repo-stat/subscriber/config/config.yaml:/config.yaml
    networks:
      - repo-stat

  processor:
    build:
      context: repo-stat
      dockerfile: Dockerfile.processor
    container_name: processor
    restart: unless-stopped
    ports:
      - "50052:50052"
    environment:
      - COLLECTOR_ADDRESS=collector:50051
    depends_on:
      - collector
    networks:
      - repo-stat

  collector:
    build:
      context: repo-stat
      dockerfile: Dockerfile.collector
    container_name: collector
    restart: unless-stopped
    ports:
      - "50051:50051"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
    networks:
      - repo-stat

  tests:
    image: tests:latest
    build:
      context: tests
    container_name: tests
    restart: "no"
    depends_on:
      - api

networks:
  repo-stat:
    driver: bridge