// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"
)

type Querier interface {
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	DeleteSubscriptions(ctx context.Context, arg DeleteSubscriptionsParams) error
	GetSubscriptionsByRepo(ctx context.Context, arg GetSubscriptionsByRepoParams) (Subscription, error)
	ListSubscriptions(ctx context.Context) ([]Subscription, error)
}

var _ Querier = (*Queries)(nil)
