// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package postgres

import (
	"context"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (owner, repo)
VALUES ($1, $2)
RETURNING id, owner, repo
`

type CreateSubscriptionParams struct {
	Owner string
	Repo  string
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.Owner, arg.Repo)
	var i Subscription
	err := row.Scan(&i.ID, &i.Owner, &i.Repo)
	return i, err
}

const deleteSubscriptions = `-- name: DeleteSubscriptions :exec
DELETE FROM subscriptions
WHERE owner = $1 AND repo = $2
`

type DeleteSubscriptionsParams struct {
	Owner string
	Repo  string
}

func (q *Queries) DeleteSubscriptions(ctx context.Context, arg DeleteSubscriptionsParams) error {
	_, err := q.db.Exec(ctx, deleteSubscriptions, arg.Owner, arg.Repo)
	return err
}

const getSubscriptionsByRepo = `-- name: GetSubscriptionsByRepo :one
SELECT id, owner, repo FROM subscriptions
WHERE owner = $1 AND repo = $2 LIMIT 1
`

type GetSubscriptionsByRepoParams struct {
	Owner string
	Repo  string
}

func (q *Queries) GetSubscriptionsByRepo(ctx context.Context, arg GetSubscriptionsByRepoParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionsByRepo, arg.Owner, arg.Repo)
	var i Subscription
	err := row.Scan(&i.ID, &i.Owner, &i.Repo)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, owner, repo FROM subscriptions
`

func (q *Queries) ListSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(&i.ID, &i.Owner, &i.Repo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
