// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: subscriber/subscriber.proto

package subscriber

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubscriberService_Ping_FullMethodName                 = "/subscriber.v1.SubscriberService/Ping"
	SubscriberService_CreateSubscription_FullMethodName   = "/subscriber.v1.SubscriberService/CreateSubscription"
	SubscriberService_DeleteSubscription_FullMethodName   = "/subscriber.v1.SubscriberService/DeleteSubscription"
	SubscriberService_GetSubscriptionsList_FullMethodName = "/subscriber.v1.SubscriberService/GetSubscriptionsList"
)

// SubscriberServiceClient is the client API for SubscriberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriberServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	CreateSubscription(ctx context.Context, in *CreateSubRequest, opts ...grpc.CallOption) (*CreateSubResponse, error)
	DeleteSubscription(ctx context.Context, in *DeleteSubRequest, opts ...grpc.CallOption) (*DeleteSubResponse, error)
	GetSubscriptionsList(ctx context.Context, in *GetSubListRequest, opts ...grpc.CallOption) (*GetSubListResponse, error)
}

type subscriberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriberServiceClient(cc grpc.ClientConnInterface) SubscriberServiceClient {
	return &subscriberServiceClient{cc}
}

func (c *subscriberServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, SubscriberService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriberServiceClient) CreateSubscription(ctx context.Context, in *CreateSubRequest, opts ...grpc.CallOption) (*CreateSubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubResponse)
	err := c.cc.Invoke(ctx, SubscriberService_CreateSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriberServiceClient) DeleteSubscription(ctx context.Context, in *DeleteSubRequest, opts ...grpc.CallOption) (*DeleteSubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSubResponse)
	err := c.cc.Invoke(ctx, SubscriberService_DeleteSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscriberServiceClient) GetSubscriptionsList(ctx context.Context, in *GetSubListRequest, opts ...grpc.CallOption) (*GetSubListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubListResponse)
	err := c.cc.Invoke(ctx, SubscriberService_GetSubscriptionsList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriberServiceServer is the server API for SubscriberService service.
// All implementations must embed UnimplementedSubscriberServiceServer
// for forward compatibility.
type SubscriberServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	CreateSubscription(context.Context, *CreateSubRequest) (*CreateSubResponse, error)
	DeleteSubscription(context.Context, *DeleteSubRequest) (*DeleteSubResponse, error)
	GetSubscriptionsList(context.Context, *GetSubListRequest) (*GetSubListResponse, error)
	mustEmbedUnimplementedSubscriberServiceServer()
}

// UnimplementedSubscriberServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscriberServiceServer struct{}

func (UnimplementedSubscriberServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSubscriberServiceServer) CreateSubscription(context.Context, *CreateSubRequest) (*CreateSubResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (UnimplementedSubscriberServiceServer) DeleteSubscription(context.Context, *DeleteSubRequest) (*DeleteSubResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSubscription not implemented")
}
func (UnimplementedSubscriberServiceServer) GetSubscriptionsList(context.Context, *GetSubListRequest) (*GetSubListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubscriptionsList not implemented")
}
func (UnimplementedSubscriberServiceServer) mustEmbedUnimplementedSubscriberServiceServer() {}
func (UnimplementedSubscriberServiceServer) testEmbeddedByValue()                           {}

// UnsafeSubscriberServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriberServiceServer will
// result in compilation errors.
type UnsafeSubscriberServiceServer interface {
	mustEmbedUnimplementedSubscriberServiceServer()
}

func RegisterSubscriberServiceServer(s grpc.ServiceRegistrar, srv SubscriberServiceServer) {
	// If the following call panics, it indicates UnimplementedSubscriberServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubscriberService_ServiceDesc, srv)
}

func _SubscriberService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriberServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriberService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriberServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriberService_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriberServiceServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriberService_CreateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriberServiceServer).CreateSubscription(ctx, req.(*CreateSubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriberService_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriberServiceServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriberService_DeleteSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriberServiceServer).DeleteSubscription(ctx, req.(*DeleteSubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubscriberService_GetSubscriptionsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriberServiceServer).GetSubscriptionsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubscriberService_GetSubscriptionsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriberServiceServer).GetSubscriptionsList(ctx, req.(*GetSubListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubscriberService_ServiceDesc is the grpc.ServiceDesc for SubscriberService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriberService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subscriber.v1.SubscriberService",
	HandlerType: (*SubscriberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _SubscriberService_Ping_Handler,
		},
		{
			MethodName: "CreateSubscription",
			Handler:    _SubscriberService_CreateSubscription_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _SubscriberService_DeleteSubscription_Handler,
		},
		{
			MethodName: "GetSubscriptionsList",
			Handler:    _SubscriberService_GetSubscriptionsList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subscriber/subscriber.proto",
}
